//
//  AAM.swift
//  XBridge10
//
//  $GP
//  AAM - Waypoint Arrival Alarm
//
//  This sentence is generated by some units to indicate the Status of arrival (entering the arrival circle, 
//  or passing the perpendicular of the course line) at the destination waypoint.

//  $GPAAM,A,A,0.10,N,WPTNME*32

//  Where:
//  AAM    Arrival Alarm
//  A      Arrival circle entered
//  A      Perpendicular passed
//  0.10   Circle radius
//  N      Nautical miles
//  WPTNME Waypoint name
//  *43    Checksum data
//
//  Created by Christopher Alford on 14/02/15.
//  Copyright (c) 2015 Yacht Tech EU. All rights reserved.
//

import Foundation
import CoreLocation

class AAM: NMEA0813Base {

    @Published var arivalCircleEntered: String = ""
    @Published var perpendicularPassed: String = ""
    @Published var circleRadius: NSDecimalNumber = 0
    @Published var nauticalMiles: String = ""
    @Published var waypointName: String = ""

    override init(rawData: String) throws {
       do {
           try super.init(rawData: rawData)
       }

        self.arivalCircleEntered = String(bytes: attributes[1], encoding: .utf8)!
        self.perpendicularPassed = String(bytes: attributes[2], encoding: .utf8)!

        if let string = String(bytes: attributes[3], encoding: .utf8) {
            self.circleRadius = NSDecimalNumber(string: string)
        } 
        self.nauticalMiles = String(bytes: attributes[4], encoding: .utf8)!
        self.waypointName = String(bytes: attributes[5], encoding: .utf8)!
    }
}
